### PR TITLE
DPRK Localizations

### PR DESCRIPTION
**Pull request by peterprd**
```ko.lproj``` is base of Korean localizations and ```ko-kr.lproj``` is South Korean localizations but the same with ```ko.lproj```. ```ko-kp.lproj``` is North Korean localization. I even translated "Nepeta" and "Github" because they don't use English.

### CODE REVIEW

**Comment by nullpixel** [comment]
Github is a brand, Nepeta is a name. Neither can be translated.

**Comment by peterprd** [comment]
@nullpixel They do.

**Comment by nullpixel** [comment]
You can’t translate names

**Comment by peterprd** [comment]
@nullpixel Name is not translated, It's transliterated.

**Pull request merged**
